### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by milot-mirdita** [indianakernick/Expr-JIT#1]
I am using tinyexpr in some of my projects since a while and Expr-JIT seems like a pretty straightforward upgrade for performance. I would really appreciate if you would add a license so I can use the library.

**Comment by indianakernick** [comment]
I might... ;-)

Can I ask what you're doing that requires high performance? If performance really matters and tinyexpr isn't cutting it then I might suggest using a JIT. Expr-JIT is not a JIT. I'm saying that because this project is really just a proof-of-concept. If it was actually serious, then I'd probably add some tests and documentation at the very least. I'd also improve parity with tinyexpr if this is meant to be a drop-in replacement that's slightly faster.

I'm guessing you found this project referenced in [tinyexpr #50](https://github.com/codeplea/tinyexpr/issues/50)? In that discussion, I also mentioned that JITs might be fast but they also pull in a lot of dependencies so a simple bytecode interpreter might be a good middle-ground. If tinyexpr is great but just isn't quite fast enough, and a JIT library would be fast but is too much of a pain to use then there is genuine need for this library. If there is a need, then that might give me the motivation to resurrect this.

**Comment by milot-mirdita** [comment]
We use tinyexpr in a couple places in our biological sequence search tool [MMseqs2](https://github.com/soedinglab/mmseqs2) (and the various related downstream tools).

Currently, tinyexpr is used for custom expression for basically TSV filtering. Its also used with some additional hacks for subsetting search results to certain species. I am integrating this taxonomic subsetting into a somewhat performance critical step and I think Expr-JIT might be a good middle ground in performance/code-complexity.

Also the small size is a huge plus and the current state of the code without any additional work from your side would already be good starting point to keep building upon it.

**Comment by indianakernick** [comment]
That's really interesting. I know nothing about biology! I added an MIT license. Be sure to let me know if there are any issues integrating this. I'll probably end up working on this project now that someone is actually using it. I'll rename it too because it's a dumb name.

**Comment by milot-mirdita** [comment]
Thank you! 

And biology/bioinformatics is fun! Tons of interesting programing challenges around :)
